/* generated by NeuronHeader.jinja2 */ 
/*
*  iaf_cond_deco2014.h
*
*  This file is part of NEST.
*
*  Copyright (C) 2004 The NEST Initiative
*
*  NEST is free software: you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation, either version 2 of the License, or
*  (at your option) any later version.
*
*  NEST is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with NEST.  If not, see <http://www.gnu.org/licenses/>.
*
*  2019-09-23 16:59:29.524089
*/
#ifndef IAF_COND_DECO2014
#define IAF_COND_DECO2014

#include "config.h"


#ifdef HAVE_GSL

// External includes:
#include <gsl/gsl_errno.h>
#include <gsl/gsl_matrix.h>
#include <gsl/gsl_odeiv.h>

// forwards the declaration of the function
/**
 * Function computing right-hand side of ODE for GSL solver.
 * @note Must be declared here so we can befriend it in class.
 * @note Must have C-linkage for passing to GSL. Internally, it is
 *       a first-class C++ function, but cannot be a member function
 *       because of the C-linkage.
 * @note No point in declaring it inline, since it is called
 *       through a function pointer.
 * @param void* Pointer to model neuron instance.
 */
extern "C" inline int iaf_cond_deco2014_dynamics( double, const double y[], double f[], void* pnode );


// Includes from nestkernel:
#include "archiving_node.h"
#include "connection.h"
#include "event.h"
#include "nest_types.h"
#include "ring_buffer.h"
#include "universal_data_logger.h"


// Includes from sli:
#include "dictdatum.h"

/* BeginDocumentation
  Name: iaf_cond_deco2014.

  Description:  
     -*- coding: utf-8 -*-

  Name: iaf_cond_deco2014 - Conductance based leaky integrate-and-fire neuron model
                            with separate excitatory AMPA & NMDA, and inhibitory GABA synapses

  Description:
  iaf_cond_delta_deco2014 is an implementation of a spiking neuron using IAF dynamics with
  conductance-based synapses.

  Sends: SpikeEvent

  Receives: SpikeEvent, CurrentEvent, DataLoggingRequest

  References:

  [1] Ponce-Alvarez A., Mantini D., Deco G., Corbetta M., Hagmann P., & Romani G. L. (2014).
  How Local Excitation-Inhibition Ratio Impacts the Whole Brain Dynamics. Journal of Neuroscience.
  34(23), 7886-7898. https://doi.org/10.1523/jneurosci.5068-13.2014

  [2] Meffin, H., Burkitt, A. N., & Grayden, D. B. (2004). An analytical
  model for the large, fluctuating synaptic conductance state typical of
  neocortical neurons in vivo. J.  Comput. Neurosci., 16, 159-175.

  [3] Bernander, O., Douglas, R. J., Martin, K. A. C., & Koch, C. (1991).
  Synaptic background activity influences spatiotemporal integration in
  single pyramidal cells.  Proc. Natl. Acad. Sci. USA, 88(24),
  11569-11573.

  [4] Kuhn, Aertsen, Rotter (2004). Neuronal Integration of Synaptic Input in
  the Fluctuation- Driven Regime. Jneurosci 24(10) 2345-2356

  Author: Dionysios Perdikis

  SeeAlso: iaf_cond_beta



  Parameters:
  The following parameters can be set in the status dictionary.
  C_m [nF]  0.2 for Inh, Capacity of the membrane
  g_m [nS]  20nS for Inh, Membrane leak conductance
  E_L [mV]  Resting potential.
  V_th [mV]  Threshold
  V_reset [mV]  Reset value of the membrane potential
  t_ref [ms]  1ms for Inh, Refractory period.
  g_AMPA_ext [nS]  2.59nS for Inh, Membrane conductance for AMPA external excitatory currents
  g_AMPA_rec [nS]  0.051nS for Inh, Membrane conductance for AMPA recurrent excitatory currents
  g_NMDA [nS]  0.16nS for Inh, Membrane conductance for NMDA recurrent excitatory currents
  g_GABA [nS]  8.51nS for Inh, Membrane conductance for GABA recurrent inhibitory currents
  E_ex [mV]  Excitatory reversal potential
  E_in [mV]  Inhibitory reversal potential
  tau_AMPA [ms]  AMPA synapse decay time
  tau_NMDA_rise [ms]  NMDA synapse rise time
  tau_NMDA_decay [ms]  NMDA synapse decay time
  tau_GABA [ms]  AMPA synapse decay time
  alpha [kHz] 
  beta [real] 
  lamda_NMDA [real] 
  I_e [pA]  External current.
  

  Dynamic state variables:
  r [integer]  counts number of tick during the refractory period
  

  Initial values:
  V_m [mV]  membrane potential
  

  References: Empty

  Sends: nest::SpikeEvent

  Receives: Spike, Current, DataLoggingRequest
*/
class iaf_cond_deco2014 : public nest::Archiving_Node{
public:
  /**
  * The constructor is only used to create the model prototype in the model manager.
  */
  iaf_cond_deco2014();

  /**
  * The copy constructor is used to create model copies and instances of the model.
  * @node The copy constructor needs to initialize the parameters and the state.
  *       Initialization of buffers and interal variables is deferred to
  *       @c init_buffers_() and @c calibrate().
  */
  iaf_cond_deco2014(const iaf_cond_deco2014 &);

  /**
  * Releases resources.
  */
  ~iaf_cond_deco2014();

  /**
   * Import sets of overloaded virtual functions.
   * @see Technical Issues / Virtual Functions: Overriding, Overloading, and
   * Hiding
   */
  using nest::Node::handles_test_event;
  using nest::Node::handle;

  /**
  * Used to validate that we can send nest::SpikeEvent to desired target:port.
  */
  nest::port send_test_event(nest::Node& target, nest::rport receptor_type, nest::synindex, bool);

  /**
  * @defgroup mynest_handle Functions handling incoming events.
  * We tell nest that we can handle incoming events of various types by
  * defining @c handle() and @c connect_sender() for the given event.
  * @{
  */
  void handle(nest::SpikeEvent &);        //! accept spikes
  void handle(nest::CurrentEvent &);      //! accept input current
  void handle(nest::DataLoggingRequest &);//! allow recording with multimeter

  nest::port handles_test_event(nest::SpikeEvent&, nest::port);
  nest::port handles_test_event(nest::CurrentEvent&, nest::port);
  nest::port handles_test_event(nest::DataLoggingRequest&, nest::port);
  /** @} */

  // SLI communication functions:
  void get_status(DictionaryDatum &) const;
  void set_status(const DictionaryDatum &);

private:
  //! Reset parameters and state of neuron.

  //! Reset state of neuron.
  void init_state_(const Node& proto);

  //! Reset internal buffers of neuron.
  void init_buffers_();

  //! Initialize auxiliary quantities, leave parameters and state untouched.
  void calibrate();

  //! Take neuron through given time interval
  void update(nest::Time const &, const long, const long);

  // The next two classes need to be friends to access the State_ class/member
  friend class nest::RecordablesMap<iaf_cond_deco2014>;
  friend class nest::UniversalDataLogger<iaf_cond_deco2014>;

  /**
  * Free parameters of the neuron.
  *
  *
  *
  * These are the parameters that can be set by the user through @c SetStatus.
  * They are initialized from the model prototype when the node is created.
  * Parameters do not change during calls to @c update() and are not reset by
  * @c ResetNetwork.
  *
  * @note Parameters_ need neither copy constructor nor @c operator=(), since
  *       all its members are copied properly by the default copy constructor
  *       and assignment operator. Important:
  *       - If Parameters_ contained @c Time members, you need to define the
  *         assignment operator to recalibrate all members of type @c Time . You
  *         may also want to define the assignment operator.
  *       - If Parameters_ contained members that cannot copy themselves, such
  *         as C-style arrays, you need to define the copy constructor and
  *         assignment operator to copy those members.
  */
  struct Parameters_{
        
        /* generated by directives/MemberDeclaration.jinja2 */ 

    //!  0.2 for Inh, Capacity of the membrane
    double C_m;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  20nS for Inh, Membrane leak conductance
    double g_m;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  Resting potential.
    double E_L;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  Threshold
    double V_th;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  Reset value of the membrane potential
    double V_reset;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  1ms for Inh, Refractory period.
    double t_ref;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  2.59nS for Inh, Membrane conductance for AMPA external excitatory currents
    double g_AMPA_ext;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  0.051nS for Inh, Membrane conductance for AMPA recurrent excitatory currents
    double g_AMPA_rec;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  0.16nS for Inh, Membrane conductance for NMDA recurrent excitatory currents
    double g_NMDA;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  8.51nS for Inh, Membrane conductance for GABA recurrent inhibitory currents
    double g_GABA;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  Excitatory reversal potential
    double E_ex;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  Inhibitory reversal potential
    double E_in;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  AMPA synapse decay time
    double tau_AMPA;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  NMDA synapse rise time
    double tau_NMDA_rise;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  NMDA synapse decay time
    double tau_NMDA_decay;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  AMPA synapse decay time
    double tau_GABA;/* generated by directives/MemberDeclaration.jinja2 */ 

    //! 
    double alpha;/* generated by directives/MemberDeclaration.jinja2 */ 

    //! 
    double beta;/* generated by directives/MemberDeclaration.jinja2 */ 

    //! 
    double lamda_NMDA;/* generated by directives/MemberDeclaration.jinja2 */ 

    //!  External current.
    double I_e;

    double __gsl_error_tol;
    /** Initialize parameters to their default values. */
    Parameters_();
  };

  /**
  * Dynamic state of the neuron.
  *
  *
  *
  * These are the state variables that are advanced in time by calls to
  * @c update(). In many models, some or all of them can be set by the user
  * through @c SetStatus. The state variables are initialized from the model
  * prototype when the node is created. State variables are reset by @c ResetNetwork.
  *
  * @note State_ need neither copy constructor nor @c operator=(), since
  *       all its members are copied properly by the default copy constructor
  *       and assignment operator. Important:
  *       - If State_ contained @c Time members, you need to define the
  *         assignment operator to recalibrate all members of type @c Time . You
  *         may also want to define the assignment operator.
  *       - If State_ contained members that cannot copy themselves, such
  *         as C-style arrays, you need to define the copy constructor and
  *         assignment operator to copy those members.
  */
  struct State_{
    //! Symbolic indices to the elements of the state vector y
    enum StateVecElems{
    
      s_AMPA_ext,
      
      s_AMPA_rec,
      
      x_NMDA,
      
      s_NMDA,
      
      s_GABA,
      //  membrane potential
      V_m,
      STATE_VEC_SIZE
    };
    //! state vector, must be C-array for GSL solver
    double ode_state[STATE_VEC_SIZE];    /* generated by directives/MemberDeclaration.jinja2 */ 

    //!  counts number of tick during the refractory period
    long r;    /* generated by directives/MemberDeclaration.jinja2 */ 

    double s_AMPA_ext_bounded;/* generated by directives/MemberDeclaration.jinja2 */ 

    double s_AMPA_rec_bounded;/* generated by directives/MemberDeclaration.jinja2 */ 

    double s_NMDA_bounded;/* generated by directives/MemberDeclaration.jinja2 */ 

    double s_GABA_bounded;/* generated by directives/MemberDeclaration.jinja2 */ 

    double I_leak;/* generated by directives/MemberDeclaration.jinja2 */ 

    double I_AMPA_ext;/* generated by directives/MemberDeclaration.jinja2 */ 

    double I_AMPA_rec;/* generated by directives/MemberDeclaration.jinja2 */ 

    double I_NMDA;/* generated by directives/MemberDeclaration.jinja2 */ 

    double I_GABA;
        State_();
  };

  /**
  * Internal variables of the neuron.
  *
  *
  *
  * These variables must be initialized by @c calibrate, which is called before
  * the first call to @c update() upon each call to @c Simulate.
  * @node Variables_ needs neither constructor, copy constructor or assignment operator,
  *       since it is initialized by @c calibrate(). If Variables_ has members that
  *       cannot destroy themselves, Variables_ will need a destructor.
  */
  struct Variables_ {    /* generated by directives/MemberDeclaration.jinja2 */ 

    //!  refractory time in steps
    long RefractoryCounts;
    
  };

  /**
    * Buffers of the neuron.
    * Ususally buffers for incoming spikes and data logged for analog recorders.
    * Buffers must be initialized by @c init_buffers_(), which is called before
    * @c calibrate() on the first call to @c Simulate after the start of NEST,
    * ResetKernel or ResetNetwork.
    * @node Buffers_ needs neither constructor, copy constructor or assignment operator,
    *       since it is initialized by @c init_nodes_(). If Buffers_ has members that
    *       cannot destroy themselves, Buffers_ will need a destructor.
    */
  struct Buffers_ {
    Buffers_(iaf_cond_deco2014 &);
    Buffers_(const Buffers_ &, iaf_cond_deco2014 &);

    /** Logger for all analog data */
    nest::UniversalDataLogger<iaf_cond_deco2014> logger_;
    
    inline nest::RingBuffer& get_spikesExc_AMPA_ext() {return spikesExc_AMPA_ext;}
    //!< Buffer incoming nSs through delay, as sum
    nest::RingBuffer spikesExc_AMPA_ext;
    double spikesExc_AMPA_ext_grid_sum_;
    
    inline nest::RingBuffer& get_spikesExc_AMPA_rec() {return spikesExc_AMPA_rec;}
    //!< Buffer incoming nSs through delay, as sum
    nest::RingBuffer spikesExc_AMPA_rec;
    double spikesExc_AMPA_rec_grid_sum_;
    
    inline nest::RingBuffer& get_spikesExc_NMDA() {return spikesExc_NMDA;}
    //!< Buffer incoming nSs through delay, as sum
    nest::RingBuffer spikesExc_NMDA;
    double spikesExc_NMDA_grid_sum_;
    
    inline nest::RingBuffer& get_spikesInh_GABA() {return spikesInh_GABA;}
    //!< Buffer incoming nSs through delay, as sum
    nest::RingBuffer spikesInh_GABA;
    double spikesInh_GABA_grid_sum_;
    
    //!< Buffer incoming pAs through delay, as sum
    nest::RingBuffer currents;
    inline nest::RingBuffer& get_currents() {return currents;}
    double currents_grid_sum_;
    /** GSL ODE stuff */
    gsl_odeiv_step* __s;    //!< stepping function
    gsl_odeiv_control* __c; //!< adaptive stepsize control function
    gsl_odeiv_evolve* __e;  //!< evolution function
    gsl_odeiv_system __sys; //!< struct describing system

    // IntergrationStep_ should be reset with the neuron on ResetNetwork,
    // but remain unchanged during calibration. Since it is initialized with
    // step_, and the resolution cannot change after nodes have been created,
    // it is safe to place both here.
    double __step;             //!< step size in ms
    double __integration_step; //!< current integration time step, updated by GSL
    };/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline long get_r() const {
    return S_.r;
  }
  inline void set_r(const long __v) {
    S_.r = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_AMPA_ext() const {
    return S_.ode_state[State_::s_AMPA_ext];
  }
  inline void set_s_AMPA_ext(const double __v) {
    S_.ode_state[State_::s_AMPA_ext] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_AMPA_rec() const {
    return S_.ode_state[State_::s_AMPA_rec];
  }
  inline void set_s_AMPA_rec(const double __v) {
    S_.ode_state[State_::s_AMPA_rec] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_x_NMDA() const {
    return S_.ode_state[State_::x_NMDA];
  }
  inline void set_x_NMDA(const double __v) {
    S_.ode_state[State_::x_NMDA] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_NMDA() const {
    return S_.ode_state[State_::s_NMDA];
  }
  inline void set_s_NMDA(const double __v) {
    S_.ode_state[State_::s_NMDA] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_GABA() const {
    return S_.ode_state[State_::s_GABA];
  }
  inline void set_s_GABA(const double __v) {
    S_.ode_state[State_::s_GABA] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_V_m() const {
    return S_.ode_state[State_::V_m];
  }
  inline void set_V_m(const double __v) {
    S_.ode_state[State_::V_m] = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_C_m() const {
    return P_.C_m;
  }
  inline void set_C_m(const double __v) {
    P_.C_m = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_g_m() const {
    return P_.g_m;
  }
  inline void set_g_m(const double __v) {
    P_.g_m = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_E_L() const {
    return P_.E_L;
  }
  inline void set_E_L(const double __v) {
    P_.E_L = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_V_th() const {
    return P_.V_th;
  }
  inline void set_V_th(const double __v) {
    P_.V_th = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_V_reset() const {
    return P_.V_reset;
  }
  inline void set_V_reset(const double __v) {
    P_.V_reset = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_t_ref() const {
    return P_.t_ref;
  }
  inline void set_t_ref(const double __v) {
    P_.t_ref = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_g_AMPA_ext() const {
    return P_.g_AMPA_ext;
  }
  inline void set_g_AMPA_ext(const double __v) {
    P_.g_AMPA_ext = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_g_AMPA_rec() const {
    return P_.g_AMPA_rec;
  }
  inline void set_g_AMPA_rec(const double __v) {
    P_.g_AMPA_rec = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_g_NMDA() const {
    return P_.g_NMDA;
  }
  inline void set_g_NMDA(const double __v) {
    P_.g_NMDA = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_g_GABA() const {
    return P_.g_GABA;
  }
  inline void set_g_GABA(const double __v) {
    P_.g_GABA = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_E_ex() const {
    return P_.E_ex;
  }
  inline void set_E_ex(const double __v) {
    P_.E_ex = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_E_in() const {
    return P_.E_in;
  }
  inline void set_E_in(const double __v) {
    P_.E_in = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_tau_AMPA() const {
    return P_.tau_AMPA;
  }
  inline void set_tau_AMPA(const double __v) {
    P_.tau_AMPA = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_tau_NMDA_rise() const {
    return P_.tau_NMDA_rise;
  }
  inline void set_tau_NMDA_rise(const double __v) {
    P_.tau_NMDA_rise = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_tau_NMDA_decay() const {
    return P_.tau_NMDA_decay;
  }
  inline void set_tau_NMDA_decay(const double __v) {
    P_.tau_NMDA_decay = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_tau_GABA() const {
    return P_.tau_GABA;
  }
  inline void set_tau_GABA(const double __v) {
    P_.tau_GABA = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_alpha() const {
    return P_.alpha;
  }
  inline void set_alpha(const double __v) {
    P_.alpha = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_beta() const {
    return P_.beta;
  }
  inline void set_beta(const double __v) {
    P_.beta = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_lamda_NMDA() const {
    return P_.lamda_NMDA;
  }
  inline void set_lamda_NMDA(const double __v) {
    P_.lamda_NMDA = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_e() const {
    return P_.I_e;
  }
  inline void set_I_e(const double __v) {
    P_.I_e = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline long get_RefractoryCounts() const {
    return V_.RefractoryCounts;
  }
  inline void set_RefractoryCounts(const long __v) {
    V_.RefractoryCounts = __v;
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_AMPA_ext_bounded() const {
    return (S_.ode_state[State_::s_AMPA_ext]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_AMPA_ext]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_AMPA_ext])));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_AMPA_rec_bounded() const {
    return (S_.ode_state[State_::s_AMPA_rec]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_AMPA_rec]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_AMPA_rec])));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_NMDA_bounded() const {
    return (S_.ode_state[State_::s_NMDA]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_NMDA]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_NMDA])));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_s_GABA_bounded() const {
    return (S_.ode_state[State_::s_GABA]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_GABA]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_GABA])));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_leak() const {
    return P_.g_m * (S_.ode_state[State_::V_m] - P_.E_L);
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_AMPA_ext() const {
    return P_.g_AMPA_ext / 1.0 * (S_.ode_state[State_::V_m] - P_.E_ex) * ((S_.ode_state[State_::s_AMPA_ext]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_AMPA_ext]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_AMPA_ext]))));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_AMPA_rec() const {
    return P_.g_AMPA_rec / 1.0 * (S_.ode_state[State_::V_m] - P_.E_ex) * ((S_.ode_state[State_::s_AMPA_rec]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_AMPA_rec]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_AMPA_rec]))));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_NMDA() const {
    return P_.g_NMDA / 1.0 * (S_.ode_state[State_::V_m] - P_.E_ex) * ((S_.ode_state[State_::s_NMDA]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_NMDA]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_NMDA]))));
  }
/* generated by directives/MemberVariableGetterSetter.jinja2 */ 
  inline double get_I_GABA() const {
    return P_.g_GABA / 1.0 * (S_.ode_state[State_::V_m] - P_.E_in) * ((S_.ode_state[State_::s_GABA]<0.0) ? (0.0*1.0) : (((S_.ode_state[State_::s_GABA]>1.0) ? (1.0*1.0) : (S_.ode_state[State_::s_GABA]))));
  }


  
  inline nest::RingBuffer& get_spikesExc_AMPA_ext() {return B_.get_spikesExc_AMPA_ext();};
  
  inline nest::RingBuffer& get_spikesExc_AMPA_rec() {return B_.get_spikesExc_AMPA_rec();};
  
  inline nest::RingBuffer& get_spikesExc_NMDA() {return B_.get_spikesExc_NMDA();};
  
  inline nest::RingBuffer& get_spikesInh_GABA() {return B_.get_spikesInh_GABA();};
  
  inline nest::RingBuffer& get_currents() {return B_.get_currents();};
  

  // Generate function header
  
  //
double bound(double) const
;
  
  /**
  * @defgroup pif_members Member variables of neuron model.
  * Each model neuron should have precisely the following four data members,
  * which are one instance each of the parameters, state, buffers and variables
  * structures. Experience indicates that the state and variables member should
  * be next to each other to achieve good efficiency (caching).
  * @note Devices require one additional data member, an instance of the @c Device
  *       child class they belong to.
  * @{
  */
  Parameters_ P_;  //!< Free parameters.
  State_      S_;  //!< Dynamic state.
  Variables_  V_;  //!< Internal Variables
  Buffers_    B_;  //!< Buffers.

  //! Mapping of recordables names to access functions
  static nest::RecordablesMap<iaf_cond_deco2014> recordablesMap_;

  friend int iaf_cond_deco2014_dynamics( double, const double y[], double f[], void* pnode );
  
/** @} */
}; /* neuron iaf_cond_deco2014 */

inline nest::port iaf_cond_deco2014::send_test_event(
    nest::Node& target, nest::rport receptor_type, nest::synindex, bool){
  // You should usually not change the code in this function.
  // It confirms that the target of connection @c c accepts @c nest::SpikeEvent on
  // the given @c receptor_type.
  nest::SpikeEvent e;
  e.set_sender(*this);
  return target.handles_test_event(e, receptor_type);
}

inline nest::port iaf_cond_deco2014::handles_test_event(nest::SpikeEvent&, nest::port receptor_type){
  
    // You should usually not change the code in this function.
    // It confirms to the connection management system that we are able
    // to handle @c SpikeEvent on port 0. You need to extend the function
    // if you want to differentiate between input ports.
    if (receptor_type != 0)
      throw nest::UnknownReceptorType(receptor_type, get_name());
    return 0;
}



inline nest::port iaf_cond_deco2014::handles_test_event(
    nest::CurrentEvent&, nest::port receptor_type){
  // You should usually not change the code in this function.
  // It confirms to the connection management system that we are able
  // to handle @c CurrentEvent on port 0. You need to extend the function
  // if you want to differentiate between input ports.
  if (receptor_type != 0)
  throw nest::UnknownReceptorType(receptor_type, get_name());
  return 0;
}

inline nest::port iaf_cond_deco2014::handles_test_event(
    nest::DataLoggingRequest& dlr, nest::port receptor_type){
  // You should usually not change the code in this function.
  // It confirms to the connection management system that we are able
  // to handle @c DataLoggingRequest on port 0.
  // The function also tells the built-in UniversalDataLogger that this node
  // is recorded from and that it thus needs to collect data during simulation.
  if (receptor_type != 0)
  throw nest::UnknownReceptorType(receptor_type, get_name());

  return B_.logger_.connect_logging_device(dlr, recordablesMap_);
}

// TODO call get_status on used or internal components
inline void iaf_cond_deco2014::get_status(DictionaryDatum &__d) const{  /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "C_m", get_C_m());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "g_m", get_g_m());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "E_L", get_E_L());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "V_th", get_V_th());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "V_reset", get_V_reset());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "t_ref", get_t_ref());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "g_AMPA_ext", get_g_AMPA_ext());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "g_AMPA_rec", get_g_AMPA_rec());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "g_NMDA", get_g_NMDA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "g_GABA", get_g_GABA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "E_ex", get_E_ex());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "E_in", get_E_in());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "tau_AMPA", get_tau_AMPA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "tau_NMDA_rise", get_tau_NMDA_rise());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "tau_NMDA_decay", get_tau_NMDA_decay());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "tau_GABA", get_tau_GABA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "alpha", get_alpha());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "beta", get_beta());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "lamda_NMDA", get_lamda_NMDA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "I_e", get_I_e());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<long>(__d, "r", get_r());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "s_AMPA_ext", get_s_AMPA_ext());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "s_AMPA_rec", get_s_AMPA_rec());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "x_NMDA", get_x_NMDA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "s_NMDA", get_s_NMDA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "s_GABA", get_s_GABA());
      /* generated by directives/WriteInDictionary.jinja2 */ 
  def<double>(__d, "V_m", get_V_m());
    

  (*__d)[nest::names::recordables] = recordablesMap_.get_list();
  
  def< double >(__d, nest::names::gsl_error_tol, P_.__gsl_error_tol);
  if ( P_.__gsl_error_tol <= 0. ){
    throw nest::BadProperty( "The gsl_error_tol must be strictly positive." );
  }
  

}

inline void iaf_cond_deco2014::set_status(const DictionaryDatum &__d){/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_C_m = get_C_m();
  updateValue<double>(__d, "C_m", tmp_C_m);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_g_m = get_g_m();
  updateValue<double>(__d, "g_m", tmp_g_m);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_E_L = get_E_L();
  updateValue<double>(__d, "E_L", tmp_E_L);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_V_th = get_V_th();
  updateValue<double>(__d, "V_th", tmp_V_th);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_V_reset = get_V_reset();
  updateValue<double>(__d, "V_reset", tmp_V_reset);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_t_ref = get_t_ref();
  updateValue<double>(__d, "t_ref", tmp_t_ref);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_g_AMPA_ext = get_g_AMPA_ext();
  updateValue<double>(__d, "g_AMPA_ext", tmp_g_AMPA_ext);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_g_AMPA_rec = get_g_AMPA_rec();
  updateValue<double>(__d, "g_AMPA_rec", tmp_g_AMPA_rec);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_g_NMDA = get_g_NMDA();
  updateValue<double>(__d, "g_NMDA", tmp_g_NMDA);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_g_GABA = get_g_GABA();
  updateValue<double>(__d, "g_GABA", tmp_g_GABA);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_E_ex = get_E_ex();
  updateValue<double>(__d, "E_ex", tmp_E_ex);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_E_in = get_E_in();
  updateValue<double>(__d, "E_in", tmp_E_in);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_tau_AMPA = get_tau_AMPA();
  updateValue<double>(__d, "tau_AMPA", tmp_tau_AMPA);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_tau_NMDA_rise = get_tau_NMDA_rise();
  updateValue<double>(__d, "tau_NMDA_rise", tmp_tau_NMDA_rise);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_tau_NMDA_decay = get_tau_NMDA_decay();
  updateValue<double>(__d, "tau_NMDA_decay", tmp_tau_NMDA_decay);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_tau_GABA = get_tau_GABA();
  updateValue<double>(__d, "tau_GABA", tmp_tau_GABA);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_alpha = get_alpha();
  updateValue<double>(__d, "alpha", tmp_alpha);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_beta = get_beta();
  updateValue<double>(__d, "beta", tmp_beta);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_lamda_NMDA = get_lamda_NMDA();
  updateValue<double>(__d, "lamda_NMDA", tmp_lamda_NMDA);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_I_e = get_I_e();
  updateValue<double>(__d, "I_e", tmp_I_e);
/* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  long tmp_r = get_r();
  updateValue<long>(__d, "r", tmp_r);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_s_AMPA_ext = get_s_AMPA_ext();
  updateValue<double>(__d, "s_AMPA_ext", tmp_s_AMPA_ext);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_s_AMPA_rec = get_s_AMPA_rec();
  updateValue<double>(__d, "s_AMPA_rec", tmp_s_AMPA_rec);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_x_NMDA = get_x_NMDA();
  updateValue<double>(__d, "x_NMDA", tmp_x_NMDA);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_s_NMDA = get_s_NMDA();
  updateValue<double>(__d, "s_NMDA", tmp_s_NMDA);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_s_GABA = get_s_GABA();
  updateValue<double>(__d, "s_GABA", tmp_s_GABA);

  /* generated by directives/ReadFromDictionaryToTmp.jinja2 */ 

  double tmp_V_m = get_V_m();
  updateValue<double>(__d, "V_m", tmp_V_m);

  // We now know that (ptmp, stmp) are consistent. We do not
  // write them back to (P_, S_) before we are also sure that
  // the properties to be set in the parent class are internally
  // consistent.
  Archiving_Node::set_status(__d);

  // if we get here, temporaries contain consistent set of properties/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_C_m(tmp_C_m);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_g_m(tmp_g_m);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_E_L(tmp_E_L);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_V_th(tmp_V_th);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_V_reset(tmp_V_reset);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_t_ref(tmp_t_ref);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_g_AMPA_ext(tmp_g_AMPA_ext);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_g_AMPA_rec(tmp_g_AMPA_rec);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_g_NMDA(tmp_g_NMDA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_g_GABA(tmp_g_GABA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_E_ex(tmp_E_ex);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_E_in(tmp_E_in);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_tau_AMPA(tmp_tau_AMPA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_tau_NMDA_rise(tmp_tau_NMDA_rise);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_tau_NMDA_decay(tmp_tau_NMDA_decay);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_tau_GABA(tmp_tau_GABA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_alpha(tmp_alpha);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_beta(tmp_beta);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_lamda_NMDA(tmp_lamda_NMDA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_I_e(tmp_I_e);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_r(tmp_r);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_s_AMPA_ext(tmp_s_AMPA_ext);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_s_AMPA_rec(tmp_s_AMPA_rec);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_x_NMDA(tmp_x_NMDA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_s_NMDA(tmp_s_NMDA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_s_GABA(tmp_s_GABA);
/* generated by directives/AssignTmpDictionaryValue.jinja2 */ 


  set_V_m(tmp_V_m);


  
  updateValue< double >(__d, nest::names::gsl_error_tol, P_.__gsl_error_tol);
  if ( P_.__gsl_error_tol <= 0. ){
    throw nest::BadProperty( "The gsl_error_tol must be strictly positive." );
  }
  
};

#endif /* #ifndef IAF_COND_DECO2014 */
#endif /* HAVE GSL */