pipeline {
    agent {
        label 'docker_build'
    }

    environment {
        FULL_DOCKER_IMAGE_NAME = 'docker-repository.codemart.ro/tvb-multiscale'
        VERSION_TAG = 'py3'
    }

    stages {
        stage('Build docker image'){
            steps {
                script {
                    LAST_SHA_TVB = sh (script: "curl -s 'https://api.github.com/repos/the-virtual-brain/tvb-root' | grep sha | head -1 | tr '\"' '_'", returnStdout: true).trim()
                    LAST_SHA_MULTISCALE = sh (script: "curl -s 'https://api.github.com/repos/the-virtual-brain/tvb-multiscale/commits' | grep sha | head -1 | tr '\"' '_'", returnStdout: true).trim()
                    def dockerfile = 'docker/Dockerfile'
                    def dockerImage = docker.build("${FULL_DOCKER_IMAGE_NAME}", "--build-arg LAST_SHA_TVB='${LAST_SHA_TVB}' --build-arg LAST_SHA_MULTISCALE='${LAST_SHA_MULTISCALE}' -f ${dockerfile} .")
                    dockerImage.push('${VERSION_TAG}')
                }
            }
        }
        stage ('Run tests in Python 3') {
            steps {
                withDockerContainer(image: '${FULL_DOCKER_IMAGE_NAME}:${VERSION_TAG}') {
                sh '''#!/bin/bash
                    source /home/docker/env/neurosci/bin/activate
                    python setup.py develop
                    pytest --cov-config .coveragerc --cov=tvb tests --cov-branch --cov-report xml:tvb_multiscale_coverage.xml --junitxml=tvb_multiscale_test_results.xml
                    exit 0
                '''
                }
                junit 'tvb_multiscale_test_results.xml'
                step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'tvb_multiscale_coverage.xml', failUnhealthy: false, failUnstable: false, maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
            }
        }
    }

    post {
        changed {
            mail to: 'paula.popa@codemart.ro',
            subject: "Jenkins Pipeline ${currentBuild.fullDisplayName} changed status",
            body: """
                Result: ${currentBuild.result}
                Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'
                Check console output at ${env.BUILD_URL}"""
        }

        success {
            echo 'Build finished successfully'
        }
    }
}