pipeline {
    agent any

    environment {
        FULL_DOCKER_IMAGE_NAME = 'thevirtualbrain/tvb-nest'
        VERSION_TAG = 'py3'
    }

    stages {
        stage ('Run tests in Python 3') {
            agent {
                docker {
                    image '${FULL_DOCKER_IMAGE_NAME}:${VERSION_TAG}'
                    alwaysPull true
                }
            }
            steps {
                sh '''#!/bin/bash
                    source /home/docker/env/neurosci/bin/activate
                    pytest --cov-config .coveragerc --cov=tvb tvb_nest/tests --cov-branch --cov-report xml:tvb_nest_coverage.xml --junitxml=tvb_nest_test_results.xml

                '''
                junit 'tvb_nest_test_results.xml'
                step([$class: 'CoberturaPublisher', autoUpdateHealth: false, autoUpdateStability: false, coberturaReportFile: 'tvb_nest_coverage.xml', failUnhealthy: false, failUnstable: false, maxNumberOfBuilds: 0, onlyStable: false, sourceEncoding: 'ASCII', zoomCoverageChart: false])
            }
        }
    }

    post {
        changed {
            mail to: 'lia.domide@codemart.ro, gabriel.florea@codemart.ro',
            subject: "Jenkins Pipeline ${currentBuild.fullDisplayName} changed status",
            body: """
                Result: ${currentBuild.result}
                Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]'
                Check console output at ${env.BUILD_URL}"""
        }

        success {
            echo 'Build finished successfully'
        }
    }
}